# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rolo/CloudInfoStamp.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class CloudInfoStamp(genpy.Message):
  _md5sum = "95edffafd888edf477d4a6245ab452a2"
  _type = "rolo/CloudInfoStamp"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header 

int32[] startRingIndex
int32[] endRingIndex

int32[]  pointColInd # point column index in range image
float32[] pointRange # point range

float32 startOrientation
float32 endOrientation
float32 orientationDiff

# Initial guess from front lidar odometry
float32 initialGuessX
float32 initialGuessY
float32 initialGuessZ
float32 initialGuessRoll
float32 initialGuessPitch
float32 initialGuessYaw
bool odomAvailable

# Point cloud messages
sensor_msgs/PointCloud2 cloud_projected  # original cloud
sensor_msgs/PointCloud2 extracted_corner    # extracted corner feature
sensor_msgs/PointCloud2 extracted_surface   # extracted surface feature
sensor_msgs/PointCloud2 extracted_normal   # extracted normal point(for back-end)
# sensor_msgs/PointCloud2 extracted_ground   # extracted ground


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field
"""
  __slots__ = ['header','startRingIndex','endRingIndex','pointColInd','pointRange','startOrientation','endOrientation','orientationDiff','initialGuessX','initialGuessY','initialGuessZ','initialGuessRoll','initialGuessPitch','initialGuessYaw','odomAvailable','cloud_projected','extracted_corner','extracted_surface','extracted_normal']
  _slot_types = ['std_msgs/Header','int32[]','int32[]','int32[]','float32[]','float32','float32','float32','float32','float32','float32','float32','float32','float32','bool','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,startRingIndex,endRingIndex,pointColInd,pointRange,startOrientation,endOrientation,orientationDiff,initialGuessX,initialGuessY,initialGuessZ,initialGuessRoll,initialGuessPitch,initialGuessYaw,odomAvailable,cloud_projected,extracted_corner,extracted_surface,extracted_normal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CloudInfoStamp, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.startRingIndex is None:
        self.startRingIndex = []
      if self.endRingIndex is None:
        self.endRingIndex = []
      if self.pointColInd is None:
        self.pointColInd = []
      if self.pointRange is None:
        self.pointRange = []
      if self.startOrientation is None:
        self.startOrientation = 0.
      if self.endOrientation is None:
        self.endOrientation = 0.
      if self.orientationDiff is None:
        self.orientationDiff = 0.
      if self.initialGuessX is None:
        self.initialGuessX = 0.
      if self.initialGuessY is None:
        self.initialGuessY = 0.
      if self.initialGuessZ is None:
        self.initialGuessZ = 0.
      if self.initialGuessRoll is None:
        self.initialGuessRoll = 0.
      if self.initialGuessPitch is None:
        self.initialGuessPitch = 0.
      if self.initialGuessYaw is None:
        self.initialGuessYaw = 0.
      if self.odomAvailable is None:
        self.odomAvailable = False
      if self.cloud_projected is None:
        self.cloud_projected = sensor_msgs.msg.PointCloud2()
      if self.extracted_corner is None:
        self.extracted_corner = sensor_msgs.msg.PointCloud2()
      if self.extracted_surface is None:
        self.extracted_surface = sensor_msgs.msg.PointCloud2()
      if self.extracted_normal is None:
        self.extracted_normal = sensor_msgs.msg.PointCloud2()
    else:
      self.header = std_msgs.msg.Header()
      self.startRingIndex = []
      self.endRingIndex = []
      self.pointColInd = []
      self.pointRange = []
      self.startOrientation = 0.
      self.endOrientation = 0.
      self.orientationDiff = 0.
      self.initialGuessX = 0.
      self.initialGuessY = 0.
      self.initialGuessZ = 0.
      self.initialGuessRoll = 0.
      self.initialGuessPitch = 0.
      self.initialGuessYaw = 0.
      self.odomAvailable = False
      self.cloud_projected = sensor_msgs.msg.PointCloud2()
      self.extracted_corner = sensor_msgs.msg.PointCloud2()
      self.extracted_surface = sensor_msgs.msg.PointCloud2()
      self.extracted_normal = sensor_msgs.msg.PointCloud2()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.startRingIndex)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.startRingIndex))
      length = len(self.endRingIndex)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.endRingIndex))
      length = len(self.pointColInd)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.pointColInd))
      length = len(self.pointRange)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.pointRange))
      _x = self
      buff.write(_get_struct_9fB3I().pack(_x.startOrientation, _x.endOrientation, _x.orientationDiff, _x.initialGuessX, _x.initialGuessY, _x.initialGuessZ, _x.initialGuessRoll, _x.initialGuessPitch, _x.initialGuessYaw, _x.odomAvailable, _x.cloud_projected.header.seq, _x.cloud_projected.header.stamp.secs, _x.cloud_projected.header.stamp.nsecs))
      _x = self.cloud_projected.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_projected.height, _x.cloud_projected.width))
      length = len(self.cloud_projected.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_projected.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_projected.is_bigendian, _x.cloud_projected.point_step, _x.cloud_projected.row_step))
      _x = self.cloud_projected.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_projected.is_dense, _x.extracted_corner.header.seq, _x.extracted_corner.header.stamp.secs, _x.extracted_corner.header.stamp.nsecs))
      _x = self.extracted_corner.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_corner.height, _x.extracted_corner.width))
      length = len(self.extracted_corner.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_corner.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_corner.is_bigendian, _x.extracted_corner.point_step, _x.extracted_corner.row_step))
      _x = self.extracted_corner.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.extracted_corner.is_dense, _x.extracted_surface.header.seq, _x.extracted_surface.header.stamp.secs, _x.extracted_surface.header.stamp.nsecs))
      _x = self.extracted_surface.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_surface.height, _x.extracted_surface.width))
      length = len(self.extracted_surface.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_surface.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_surface.is_bigendian, _x.extracted_surface.point_step, _x.extracted_surface.row_step))
      _x = self.extracted_surface.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.extracted_surface.is_dense, _x.extracted_normal.header.seq, _x.extracted_normal.header.stamp.secs, _x.extracted_normal.header.stamp.nsecs))
      _x = self.extracted_normal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_normal.height, _x.extracted_normal.width))
      length = len(self.extracted_normal.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_normal.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_normal.is_bigendian, _x.extracted_normal.point_step, _x.extracted_normal.row_step))
      _x = self.extracted_normal.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.extracted_normal.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cloud_projected is None:
        self.cloud_projected = sensor_msgs.msg.PointCloud2()
      if self.extracted_corner is None:
        self.extracted_corner = sensor_msgs.msg.PointCloud2()
      if self.extracted_surface is None:
        self.extracted_surface = sensor_msgs.msg.PointCloud2()
      if self.extracted_normal is None:
        self.extracted_normal = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.startRingIndex = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.endRingIndex = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pointColInd = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pointRange = s.unpack(str[start:end])
      _x = self
      start = end
      end += 49
      (_x.startOrientation, _x.endOrientation, _x.orientationDiff, _x.initialGuessX, _x.initialGuessY, _x.initialGuessZ, _x.initialGuessRoll, _x.initialGuessPitch, _x.initialGuessYaw, _x.odomAvailable, _x.cloud_projected.header.seq, _x.cloud_projected.header.stamp.secs, _x.cloud_projected.header.stamp.nsecs,) = _get_struct_9fB3I().unpack(str[start:end])
      self.odomAvailable = bool(self.odomAvailable)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_projected.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_projected.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_projected.height, _x.cloud_projected.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_projected.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_projected.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_projected.is_bigendian, _x.cloud_projected.point_step, _x.cloud_projected.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_projected.is_bigendian = bool(self.cloud_projected.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_projected.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_projected.is_dense, _x.extracted_corner.header.seq, _x.extracted_corner.header.stamp.secs, _x.extracted_corner.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_projected.is_dense = bool(self.cloud_projected.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_corner.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_corner.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_corner.height, _x.extracted_corner.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_corner.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_corner.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_corner.is_bigendian, _x.extracted_corner.point_step, _x.extracted_corner.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_corner.is_bigendian = bool(self.extracted_corner.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_corner.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.extracted_corner.is_dense, _x.extracted_surface.header.seq, _x.extracted_surface.header.stamp.secs, _x.extracted_surface.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.extracted_corner.is_dense = bool(self.extracted_corner.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_surface.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_surface.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_surface.height, _x.extracted_surface.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_surface.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_surface.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_surface.is_bigendian, _x.extracted_surface.point_step, _x.extracted_surface.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_surface.is_bigendian = bool(self.extracted_surface.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_surface.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.extracted_surface.is_dense, _x.extracted_normal.header.seq, _x.extracted_normal.header.stamp.secs, _x.extracted_normal.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.extracted_surface.is_dense = bool(self.extracted_surface.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_normal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_normal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_normal.height, _x.extracted_normal.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_normal.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_normal.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_normal.is_bigendian, _x.extracted_normal.point_step, _x.extracted_normal.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_normal.is_bigendian = bool(self.extracted_normal.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_normal.data = str[start:end]
      start = end
      end += 1
      (self.extracted_normal.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.extracted_normal.is_dense = bool(self.extracted_normal.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.startRingIndex)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.startRingIndex.tostring())
      length = len(self.endRingIndex)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.endRingIndex.tostring())
      length = len(self.pointColInd)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.pointColInd.tostring())
      length = len(self.pointRange)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.pointRange.tostring())
      _x = self
      buff.write(_get_struct_9fB3I().pack(_x.startOrientation, _x.endOrientation, _x.orientationDiff, _x.initialGuessX, _x.initialGuessY, _x.initialGuessZ, _x.initialGuessRoll, _x.initialGuessPitch, _x.initialGuessYaw, _x.odomAvailable, _x.cloud_projected.header.seq, _x.cloud_projected.header.stamp.secs, _x.cloud_projected.header.stamp.nsecs))
      _x = self.cloud_projected.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cloud_projected.height, _x.cloud_projected.width))
      length = len(self.cloud_projected.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.cloud_projected.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.cloud_projected.is_bigendian, _x.cloud_projected.point_step, _x.cloud_projected.row_step))
      _x = self.cloud_projected.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.cloud_projected.is_dense, _x.extracted_corner.header.seq, _x.extracted_corner.header.stamp.secs, _x.extracted_corner.header.stamp.nsecs))
      _x = self.extracted_corner.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_corner.height, _x.extracted_corner.width))
      length = len(self.extracted_corner.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_corner.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_corner.is_bigendian, _x.extracted_corner.point_step, _x.extracted_corner.row_step))
      _x = self.extracted_corner.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.extracted_corner.is_dense, _x.extracted_surface.header.seq, _x.extracted_surface.header.stamp.secs, _x.extracted_surface.header.stamp.nsecs))
      _x = self.extracted_surface.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_surface.height, _x.extracted_surface.width))
      length = len(self.extracted_surface.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_surface.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_surface.is_bigendian, _x.extracted_surface.point_step, _x.extracted_surface.row_step))
      _x = self.extracted_surface.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.extracted_surface.is_dense, _x.extracted_normal.header.seq, _x.extracted_normal.header.stamp.secs, _x.extracted_normal.header.stamp.nsecs))
      _x = self.extracted_normal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.extracted_normal.height, _x.extracted_normal.width))
      length = len(self.extracted_normal.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.extracted_normal.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.extracted_normal.is_bigendian, _x.extracted_normal.point_step, _x.extracted_normal.row_step))
      _x = self.extracted_normal.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.extracted_normal.is_dense
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cloud_projected is None:
        self.cloud_projected = sensor_msgs.msg.PointCloud2()
      if self.extracted_corner is None:
        self.extracted_corner = sensor_msgs.msg.PointCloud2()
      if self.extracted_surface is None:
        self.extracted_surface = sensor_msgs.msg.PointCloud2()
      if self.extracted_normal is None:
        self.extracted_normal = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.startRingIndex = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.endRingIndex = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pointColInd = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pointRange = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 49
      (_x.startOrientation, _x.endOrientation, _x.orientationDiff, _x.initialGuessX, _x.initialGuessY, _x.initialGuessZ, _x.initialGuessRoll, _x.initialGuessPitch, _x.initialGuessYaw, _x.odomAvailable, _x.cloud_projected.header.seq, _x.cloud_projected.header.stamp.secs, _x.cloud_projected.header.stamp.nsecs,) = _get_struct_9fB3I().unpack(str[start:end])
      self.odomAvailable = bool(self.odomAvailable)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cloud_projected.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cloud_projected.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cloud_projected.height, _x.cloud_projected.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cloud_projected.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.cloud_projected.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.cloud_projected.is_bigendian, _x.cloud_projected.point_step, _x.cloud_projected.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.cloud_projected.is_bigendian = bool(self.cloud_projected.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cloud_projected.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.cloud_projected.is_dense, _x.extracted_corner.header.seq, _x.extracted_corner.header.stamp.secs, _x.extracted_corner.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.cloud_projected.is_dense = bool(self.cloud_projected.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_corner.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_corner.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_corner.height, _x.extracted_corner.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_corner.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_corner.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_corner.is_bigendian, _x.extracted_corner.point_step, _x.extracted_corner.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_corner.is_bigendian = bool(self.extracted_corner.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_corner.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.extracted_corner.is_dense, _x.extracted_surface.header.seq, _x.extracted_surface.header.stamp.secs, _x.extracted_surface.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.extracted_corner.is_dense = bool(self.extracted_corner.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_surface.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_surface.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_surface.height, _x.extracted_surface.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_surface.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_surface.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_surface.is_bigendian, _x.extracted_surface.point_step, _x.extracted_surface.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_surface.is_bigendian = bool(self.extracted_surface.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_surface.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.extracted_surface.is_dense, _x.extracted_normal.header.seq, _x.extracted_normal.header.stamp.secs, _x.extracted_normal.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.extracted_surface.is_dense = bool(self.extracted_surface.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.extracted_normal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.extracted_normal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.extracted_normal.height, _x.extracted_normal.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extracted_normal.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.extracted_normal.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.extracted_normal.is_bigendian, _x.extracted_normal.point_step, _x.extracted_normal.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.extracted_normal.is_bigendian = bool(self.extracted_normal.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.extracted_normal.data = str[start:end]
      start = end
      end += 1
      (self.extracted_normal.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.extracted_normal.is_dense = bool(self.extracted_normal.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9fB3I = None
def _get_struct_9fB3I():
    global _struct_9fB3I
    if _struct_9fB3I is None:
        _struct_9fB3I = struct.Struct("<9fB3I")
    return _struct_9fB3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
