# pcd_to_pointcloud:
#   frame_id: $(arg frame_id)
#   topic: $(arg pcd_topic)
#   latch: true

prior_pose_node:
  pose_topic: /move_base_simple/goal # For manual debug, useless for running
  # pose_cov_topic: /initialpose
  pose_cov_topic: /fused_odom_future_local_marker
  # frame_id: map
  frame_id: base_link
  child_frame_id: prior_base
  mesh_resource: package://rolo/resource/meshes/vehicle.dae
  marker_scale: 1.0

  # Vehicle model
  vehicle_size_xy: 2.0

  vehicle_com_z: 1.0
  wheel_xy: [-0.747, 0.463,   
             0.713, 0.463,   
             0.747, -0.463,   
             -0.713, -0.463]  # [x1, y1, x2, y2, ...] in body frame
  
  # Body frame (CoM) -> LiDAR frame
  lidarOffsetTrans: [0, 0, 0.94]
  lidarOffsetRot: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
  # Solver
  k_spring: 20.0
  g: 1.0
  max_iters: 50
  lm_lambda: 0.01
  tol_cost: 1.0e-12
  tol_step: 1.0e-10
  ground_avg_radius: 0.3
  ground_min_neighbors: 5
  tolerance_z_min: -8.0
  tolerance_z_max: 8.0
  tolerance_roll: 0.5
  tolerance_pitch: 0.5
  tolerance_wheel_distance: 0.1
  publish_tf: true
  publish_model_marker: true
  model_marker_width: 0.05
  verbose: false

  # Mesh alignment (optional)
  mesh_offset: [0.0, 0.0, -1.0]
  mesh_rpy: [0.0, 0.0, 0.0]
  mesh_wheel_points: [-0.747, 0.463, 0.0,   0.713, 0.463, 0.0,   0.747, -0.463, 0.0,   -0.713, -0.463, 0.0]  # [x1, y1, z1, x2, y2, z2, ...]

prior_factor:
  priorFactorEnableFlag: true
  priorFactorFrequency: 5.0     # Hz
  groundPatchSize: 20.0
  nearPriorRadius: 0.99999
  priorFitnessScore: 0.05
  priorTimeValidation: 30.0
  priorRangeValidation: 30.0
  priorRotDiffTolerance: 5.0 # deg
  priorTransDiffTolerance: 1.0 # m
  priorFactorWeight: 5000
  priorSyncedInterval: 1.0
